### ISSUE TITLE
Colour-blindness

### ISSUE THREAD

**Issue by GiladAmar** [nealmckee/penumbra#1]
Do you have any suggestions as to which palette is more friendly with color-bind folk?
Love the look myself, nor am I colour-blind, but thought this might be a handy addition for others.

Nice work:-)

**Comment by nealmckee** [comment]
The issue with CVD is that if I recall correctly, people who are affected can in the most extreme case only readily distinguish no more than 7 different colours (using chroma _and_ hue, so including greys). This makes it vital to also use luminance and overall very hard to find enough sufficiently distinct colours at all.

I’m also working on a mathematically optimised palette for CVD that might arguably also be optimal for syntax highlighting but that might take a while.

Until then, there are a lot of hand-picked/manually optimized versions out there:
From data visualisations there are Okabe-Ito (https://www.nature.com/articles/nmeth.1618) and Paul Tol’s palettes (https://personal.sron.nl/~pault/).
For VSCode, simply put “color blind” in the extension search and there are a couple of options straight away.
