### ISSUE TITLE
[Help Wanted] Selection Color?

### ISSUE THREAD

**Issue by aidancz** [nealmckee/penumbra#17]
Currently I'm using "Dark Contrast++"

as for text selection, i simply change the background to shade+, is it the correct color?

![pic-selected-240116-1621-13](https://github.com/nealmckee/penumbra/assets/97080720/e554efb9-0b58-457b-b048-dce6c0678f0b)

in "Intended Usage" section, it is recommended that use "sun" and "shade-" as selection colors, but it is very weird:

![pic-selected-240116-1624-48](https://github.com/nealmckee/penumbra/assets/97080720/bc2c4993-5251-4568-83c9-2c602ebd32b8)

so what is the intended usage for selection?

**Comment by nealmckee** [comment]
I think for the VSCode theme, I used Sun with transparency to get an effect similar to using Shade+ (but with more warmth).
If you do not want to use transparency, it’s meant to be used inverted, so with the text in Shade- and the highlighting in Sun. This can have very high contrast though.

In general, all of these are only the _intended_ use where generally the Sun and Shade colors are meant to be used to contrast each other naturally. So for example something being selected is like “light shining onto it”, either by use of transparency, or by “casting hard shadows” along the “contours” of the text.
Readability should always come first though!
