### ISSUE TITLE
Publishing to Open VSX Registry

### ISSUE THREAD

**Issue by fenuks** [nealmckee/penumbra#5]
Fully open source versions of VSCode (like VSCodium) aren't allowed to use Microsoft's marketplace. Could you publish Penumba to https://open-vsx.org/ as well?

**Comment by nealmckee** [comment]
The process seems surprisingly involved, but I’ll get on it very soon.

**Comment by nealmckee** [comment]
It’s now available on Open VSX: https://open-vsx.org/extension/PenumbraTheme/penumbra
